changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "Breaking Changes 💥"
      labels:
        - breaking
    - title: "Features 🚀"
      labels:
        - feature
    - title: "Bug Fixes 🐛"
      labels:
        - bug
    - title: "Documentation 📚"
      labels:
        - documentation
        - docs
    - title: "Other changes"
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: "Dependencies 📃"
      labels:
        - dependencies
